---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.61.2

      helm:
        valueFiles:
          - $values/release/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-grafana.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
